// apps/horizontal-catalog-mfe/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'micro-frontends-thesis-apps-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'horizontal-catalog-mfe';
}

<!-- <router-outlet></router-outlet> -->

<section class="esh-catalog-filters">
  <div class="container">
    <pre>errorReceived: {{ !!errorReceived | json }}</pre>
    <div
      *ngIf="errorReceived"
      class="alert alert-warning esh-catalog-alert"
      role="alert"
    >
      Error requesting catalog products, please try later on
    </div>
    <!-- <div class="esh-catalog-filters-wrapper d-flex align-items-end mt-3">
      <div class="esh-catalog-filter-wrapper">
        <label class="esh-catalog-label" for="brand">Brand</label>
        <select
          class="esh-catalog-filter form-control"
          id="brand"
          (change)="onBrandFilterChanged($event)"
        >
          <option *ngFor="let brand of brands" [value]="brand.id">
            {{ brand.brand }}
          </option>
        </select>
      </div>
      <div class="esh-catalog-filter-wrapper">
        <label class="esh-catalog-label" for="type">Type</label>
        <select
          class="esh-catalog-filter form-control"
          id="type"
          (change)="onTypeFilterChanged($event)"
        >
          <option *ngFor="let type of types" [value]="type.id">
            {{ type.type }}
          </option>
        </select>
      </div>
      <button
        type="button"
        class="btn btn-primary"
        (click)="onFilterApplied($event)"
      >
        Apply
      </button>
    </div> -->
  </div>
</section>

<div class="container">
  <div *ngIf="catalog?.data?.length && catalog!.data.length > 0">
    <!-- <esh-pager
      [model]="paginationInfo"
      (changed)="onPageChanged($event)"
    ></esh-pager> -->

    <div class="esh-catalog-items row">
      <div
        class="col-12 col-sm-6 col-md-4 col-lg-3"
        *ngFor="let item of catalog?.data"
      >
        <div
          [ngClass]="{
            'esh-catalog-item': true,
            'is-disabled': !authenticated
          }"
          (click)="addToCart(item)"
        >
          <div class="esh-catalog-thumbnail-wrapper">
            <div
              class="esh-catalog-thumbnail-icon d-flex justify-content-center"
            >
              <img
                class="esh-catalog-thumbnail-icon-svg"
                src="assets/images/add.svg"
              />
            </div>
            <img class="esh-catalog-thumbnail" src="{{ item.pictureUri }}" />
          </div>
          <div
            class="esh-catalog-details d-flex justify-content-between align-items-center"
          >
            <div class="esh-catalog-name ml-3">
              <span>{{ item.name }}</span>
            </div>
            <div class="esh-catalog-price mr-3">
              <span>{{ item.price | number: '1.2-2' }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- <esh-pager
      [model]="paginationInfo"
      (changed)="onPageChanged($event)"
    ></esh-pager> -->
  </div>
  <div *ngIf="catalog?.data?.length === 0">
    <span>THERE ARE NO RESULTS THAT MATCH YOUR SEARCH</span>
  </div>
</div>

// apps/horizontal-basket-mfe/src/app/app.tsx
export function App() {
  return (
    <>
      <div className="hb-basket mt-3 mb-3">
        <div className="container">
          {/* <div *ngFor="let errorMessage of errorMessages">
              <div className="hb-basket-alert row">
                  <div className="alert alert-warning" role="alert">&nbsp;{{errorMessage}}</div>
              </div>
          </div> */}

          <div className="row">
            <div className="col-12">
              <h2 className="hb-basket-title">Your shopping bag</h2>
            </div>
            <div className="col-12">
              <div className="hb-basket-items row">
                {/* *ngFor="let item of basket?.items" */}
                <div className="col-12">
                  <article className="hb-basket-item">
                    <div className="hb-basket-thumbnail-wrapper">
                      {/* (click)="deleteItem(item.id)" */}
                      <div className="hb-basket-delete">
                        <button type="button" className="btn btn-outline-secondary">
                          <img className="hb-basket-delete-svg" src="assets/icons/bag-dash.svg" alt="Delete" />
                        </button>
                      </div>
                      {/* {{item.pictureUrl}} */}
                      <img className="hb-basket-thumbnail" src="" alt="Product Name" />
                    </div>
                    <div className="hb-basket-title">
                      Product Name
                      {/* {{item.productName}} */}
                    </div>
                    <div className="hb-basket-description divider d-flex align-items-center justify-content-between">
                      <div className="">
                        $123
                        {/* {{item.unitPrice | number:'.2-2'}} */}
                      </div>
                      <div className="hb-basket-buttons d-flex justify-content-center">
                        {/* [ngClass]="{'hb-basket-button': true, 'is-disabled': item.quantity === 1}" 
                                        (click)="itemQuantityChanged(item, item.quantity-1)" */}
                        <div className="btn-group">
                          <button type="button" className="hb-basket-button btn btn-outline-secondary">
                            <img className="hb-basket-button-svg" src="assets/icons/dash.svg" alt="Less" />
                          </button>
                          <button type="button" className="hb-basket-quantity btn btn-outline-secondary" disabled>
                            1{/* {{item.quantity}} */}
                          </button>
                          <button type="button" className="hb-basket-button btn btn-outline-secondary">
                            <img className="hb-basket-button-svg" src="assets/icons/plus.svg" alt="Less" />
                          </button>
                        </div>
                        {/* <button></button>
                        (click)="itemQuantityChanged(item, item.quantity+1)"
                        <button className="hb-basket-button">
                          <img className="hb-basket-button-svg" src="assets/icons/plus.svg" alt="More" />
                        </button> */}
                      </div>
                      <div className="hb-basket-price">
                        $123
                        {/* {{(item.unitPrice * item.quantity) | number:'.2-2'}} */}
                      </div>
                    </div>
                    {/* *ngIf="item.oldUnitPrice > 0" */}
                    {/* <div className="">
                      {{item.oldUnitPrice}}
                      &nbsp;Note that the price of this article changed in our Catalog. The old price when you originally added it to the
                      basket was $ 123
                    </div> */}
                  </article>
                </div>
              </div>
            </div>
            <div className="col-12">
              <div className="hb-basket-checkout">
                {/* {{basket?.items ? basket?.items.length : 0}} */}
                <div className="mb-3 u-text-sm">(3 items)</div>

                <div className="d-flex justify-content-between align-items-center font-weight-bolder">
                  <div>TOTAL</div>
                  <div>
                    $123
                    {/* ${{totalPrice | number:'.2-2'}} */}
                  </div>
                </div>
              </div>

              <div className="divider u-background-brightest bt-4">
                <div>
                  {/* (click)="checkOut($event)" */}
                  <button className="btn btn-primary w-100">Checkout</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div />
    </>
  );
}

export default App;
